# Port Aplikasi
quarkus.http.port=8084

# Konfigurasi Database PostgreSQL
#quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

# Manajemen Skema Database (Gunakan 'update' untuk tahap development awal)
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true