# Port Aplikasi
quarkus.http.port=8084

# Konfigurasi Database PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=106720Frans.
quarkus.datasource.jdbc.url=jdbc:postgresql://db.gczbqjzebbrcablgjavu.supabase.co:5432/postgres?user=postgres&password=106720Frans.

# Manajemen Skema Database (Gunakan 'update' untuk tahap development awal)
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true


quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
quarkus.http.cors.headers=origin,content-type,accept,authorization
